### ISSUE TITLE
famous.css - had to manually copy to client folder

### ISSUE THREAD

**Issue by scarbies** [raix/Meteor-famono#105]
@raix et al.

Im having to manually copy famous.css like so for this package to work for me?

``` 
cp .meteor/.famono-base/lib/famous/core/famous.css client/css
```
Otherwise the famous-surface / famous-group / etc. classes are not found and you get weird behaviour. Very confusing, took me a while to figure out my views were broken. 

Using it with **gadicohen:famous-views** in a seemingly standard way. Not sure what Ive done wrong!?

Thanks in advance.

**Comment by gadicc** [comment]
Make sure you have these lines in some client side JS to make sure the famono imports the CSS:

```js
 // Rig some famo.us deps
famous.polyfills;
famous.core.famous;
```

As per famono README or end of famous-views Quick Start.

**Comment by scarbies** [comment]
Ash sorry, my bad. A warning may of been good :) Thanks
