### ISSUE TITLE
Famono server-side error on Modulus.io

### ISSUE THREAD

**Issue by siegesmund** [raix/Meteor-famono#98]
Deploying to modulus creates the following error on the server side:
Famono-server: Error lib folder not found "/mnt/.famono-base/lib"

**Comment by mmw109Git** [comment]
This issue also occurs on Meteor.com

https://groups.google.com/forum/#!topic/meteor-talk/KlYeZYmGfwM

[Thu Jan 22 2015 08:58:52 GMT+0000 (UTC)] INFO Famono-server: Error lib folder
not found "/meteor/containers/.famono-base/lib"

**Comment by fredevery** [comment]
I am getting the same issue on a deploy to AWS.
